# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'midTerm2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for midTerm2
  pod "SwiftSpinner"
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'

end
